[package]
name = "direct2d"
version = "0.1.0"
authors = ["Conni Hilarides <connorcpu@live.com>"]
description = "A safe abstraction for drawing with Direct2D"
repository = "https://github.com/Connicpu/direct2d-rs"
documentation = "https://docs.rs/direct2d/*/x86_64-pc-windows-msvc/direct2d/"
license = "MIT/Apache-2.0"

[target.'cfg(windows)'.dependencies]
directwrite = "0.0.9"
wio = "0.2"
dxgi = "0.1"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["d2d1_1", "dwrite", "winbase", "libloaderapi", "errhandlingapi", "winuser"]

[target.'cfg(windows)'.dev-dependencies]
lazy_static = "1.0"
