[package]
name = "direct2d"
version = "0.0.6"
authors = ["Conni Hilarides <connorcpu@live.com>"]
description = "A safe abstraction for drawing with Direct2D"
repository = "https://github.com/Connorcpu/direct2d-rs"
documentation = "https://docs.rs/direct2d/0.0.6/x86_64-pc-windows-msvc/direct2d/"
license = "MIT/Apache-2.0"

[dependencies]
winapi = "0.2"
uuid = "0.4"
kernel32-sys = "0.2"
user32-sys = "0.2"
directwrite = "0.0.6"
