[package]
name = "direct2d"
version = "0.0.2"
authors = ["Connor Hilarides <connorcpu@live.com>"]
description = "A safe abstraction for drawing Direct2D"
repository = "https://github.com/Connorcpu/direct2d-rs"
license = "MIT"

[dependencies]
winapi = "0.2"
uuid = "0.1"
kernel32-sys = "0.2"
user32-sys = "0.1"
directwrite = "0.0.1"
